---
app_name: node-service
app_user: ubuntu
app_group: ubuntu
app_directory: /opt/node-service
app_repository: https://github.com/rumeysatr/nodejs-service-deployment.git
app_branch: main
app_port: 3000
