- name: Docker kurulum script'ini indir ve çalıştır
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: docker compose plugin mevcut mu kontrol et
  ansible.builtin.command: docker compose version
  register: compose_check
  changed_when: false
  failed_when: false

- name: Kullanıcıyı docker grubuna ekle
  ansible.builtin.user:
    name: "{{ app_user }}"
    groups: docker
    append: true

- name: Uygulama dizinini oluştur
  ansible.builtin.file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"
    mode: "0755"

- name: docker-compose.yml'i oluştur (template)
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
    mode: "0644"

- name: .env dosyasını oluştur
  ansible.builtin.copy:
    dest: "{{ app_directory }}/.env"
    owner: "{{ app_user }}"
    mode: "0600"
    content: |
      PORT={{ app_port }}
      MONGO_URI={{ mongo_uri }}

- name: nginx dizinini oluştur
  ansible.builtin.file:
    path: "{{ app_directory }}/nginx"
    state: directory
    owner: "{{ app_user }}"
    mode: "0755"

- name: nginx.conf'u kopyala
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../nginx/nginx.conf" # repo kökündeki tek kaynak
    dest: "{{ app_directory }}/nginx/nginx.conf"
    mode: "0644"

- name: Docker imajını çek
  ansible.builtin.command: docker compose pull
  args:
    chdir: "{{ app_directory }}"

- name: Konteynerleri çalıştır
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ app_directory }}"
